import React, { useState } from 'react';
import { Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import colors from '@/constants/colors';

const countries = [{ name: 'United States', users: '18.4K', pct: 72 }, { name: 'Saudi Arabia', users: '9.8K', pct: 48 }, { name: 'United Kingdom', users: '6.2K', pct: 31 }, { name: 'Canada', users: '4.1K', pct: 21 }];
const retention = [{ label: 'Day 1', value: 42 }, { label: 'Day 7', value: 24 }, { label: 'Day 14', value: 17 }, { label: 'Day 30', value: 11 }];

export default function InsightsScreen() {
  const insets = useSafeAreaInsets();
  const [active, setActive] = useState<'retention' | 'geo'>('retention');
  return (
    <ScrollView style={styles.screen} contentContainerStyle={[styles.content, { paddingTop: Math.max(insets.top, 18) + 8, paddingBottom: Platform.OS === 'web' ? 34 : 28 }]} showsVerticalScrollIndicator={false}>
      <View><Text style={styles.eyebrow}>ANALYTICS LAB</Text><Text style={styles.title}>Insights</Text><Text style={styles.subtitle}>Understand what keeps users coming back.</Text></View>
      <View style={styles.segment}><Pressable onPress={() => setActive('retention')} style={[styles.segmentItem, active === 'retention' && styles.segmentActive]}><Text style={[styles.segmentText, active === 'retention' && styles.segmentTextActive]}>Retention</Text></Pressable><Pressable onPress={() => setActive('geo')} style={[styles.segmentItem, active === 'geo' && styles.segmentActive]}><Text style={[styles.segmentText, active === 'geo' && styles.segmentTextActive]}>Geography</Text></Pressable></View>
      {active === 'retention' ? <><View style={styles.insightHero}><View><Text style={styles.cardEyebrow}>COHORT RETENTION</Text><Text style={styles.heroValue}>42%</Text><Text style={styles.cardMuted}>Day 1 retention across all apps</Text></View><View style={styles.ring}><Text style={styles.ringText}>+2.1%</Text></View></View><View style={styles.card}><View style={styles.cardHeader}><View><Text style={styles.cardTitle}>Retention curve</Text><Text style={styles.cardMuted}>Calculated from active user cohorts</Text></View><Feather name="info" size={16} color={colors.light.mutedForeground} /></View>{retention.map((item) => <View style={styles.retentionRow} key={item.label}><Text style={styles.retentionLabel}>{item.label}</Text><View style={styles.track}><View style={[styles.fill, { width: `${item.value * 2}%` }]} /></View><Text style={styles.retentionValue}>{item.value}%</Text></View>)}</View></> : <><View style={styles.geoHero}><Feather name="globe" size={23} color={colors.light.primary} /><View><Text style={styles.heroValue}>38.5K</Text><Text style={styles.cardMuted}>users across 27 countries</Text></View></View><View style={styles.card}><View style={styles.cardHeader}><View><Text style={styles.cardTitle}>Top countries</Text><Text style={styles.cardMuted}>Active users · last 30 days</Text></View><Feather name="map-pin" size={16} color={colors.light.mutedForeground} /></View>{countries.map((country, index) => <View key={country.name} style={styles.countryRow}><Text style={styles.countryIndex}>0{index + 1}</Text><View style={styles.countryInfo}><Text style={styles.countryName}>{country.name}</Text><View style={styles.track}><View style={[styles.fill, { width: `${country.pct}%`, backgroundColor: index === 0 ? colors.light.primary : '#6ED6B2' }]} /></View></View><Text style={styles.countryUsers}>{country.users}</Text></View>)}</View></>}
      <View style={styles.note}><Feather name="check-circle" size={16} color="#6ED6B2" /><Text style={styles.noteText}>Metrics are sourced from connected Firebase projects when available. Calculated metrics are labeled for accuracy.</Text></View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.light.background }, content: { paddingHorizontal: 18, gap: 14 }, eyebrow: { color: colors.light.mutedForeground, fontSize: 11, fontWeight: '700', letterSpacing: 1.2 }, title: { color: colors.light.foreground, fontSize: 25, fontWeight: '700', marginTop: 5 }, subtitle: { color: colors.light.mutedForeground, fontSize: 12, marginTop: 5 }, segment: { flexDirection: 'row', backgroundColor: colors.light.secondary, padding: 4, borderRadius: 13 }, segmentItem: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 10 }, segmentActive: { backgroundColor: colors.light.card }, segmentText: { color: colors.light.mutedForeground, fontSize: 12, fontWeight: '600' }, segmentTextActive: { color: colors.light.foreground }, insightHero: { backgroundColor: '#172A43', borderRadius: 20, padding: 19, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, cardEyebrow: { color: '#9FB1C8', fontSize: 10, letterSpacing: 1, fontWeight: '700' }, heroValue: { color: colors.light.foreground, fontSize: 34, fontWeight: '700', marginTop: 6 }, cardMuted: { color: colors.light.mutedForeground, fontSize: 11, marginTop: 4 }, ring: { width: 64, height: 64, borderRadius: 32, borderWidth: 6, borderColor: colors.light.primary, borderLeftColor: '#FFFFFF18', alignItems: 'center', justifyContent: 'center' }, ringText: { color: '#6ED6B2', fontSize: 11, fontWeight: '700' }, geoHero: { backgroundColor: '#172A43', borderRadius: 20, padding: 19, flexDirection: 'row', alignItems: 'center', gap: 14 }, card: { backgroundColor: colors.light.card, borderRadius: 20, padding: 17, borderWidth: 1, borderColor: colors.light.border, gap: 18 }, cardHeader: { flexDirection: 'row', justifyContent: 'space-between' }, cardTitle: { color: colors.light.foreground, fontSize: 15, fontWeight: '700' }, retentionRow: { flexDirection: 'row', alignItems: 'center', gap: 10 }, retentionLabel: { color: colors.light.mutedForeground, width: 41, fontSize: 11 }, track: { flex: 1, height: 8, backgroundColor: colors.light.secondary, borderRadius: 5, overflow: 'hidden' }, fill: { height: '100%', backgroundColor: colors.light.primary, borderRadius: 5 }, retentionValue: { color: colors.light.foreground, width: 34, textAlign: 'right', fontSize: 12, fontWeight: '700' }, countryRow: { flexDirection: 'row', alignItems: 'center', gap: 10 }, countryIndex: { color: colors.light.mutedForeground, fontSize: 10, width: 18 }, countryInfo: { flex: 1, gap: 7 }, countryName: { color: colors.light.foreground, fontSize: 12, fontWeight: '600' }, countryUsers: { color: colors.light.foreground, fontSize: 12, fontWeight: '700', width: 40, textAlign: 'right' }, note: { flexDirection: 'row', gap: 8, alignItems: 'flex-start', backgroundColor: '#14251F', padding: 13, borderRadius: 14 }, noteText: { flex: 1, color: '#91C9B4', fontSize: 10, lineHeight: 15 },
});